### ISSUE TITLE
Feature request: single certificate with multiple domain names

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [bringnow/docker-letsencrypt-manager#1]
Managing certificates with multiple domain names is a crucial requierement for many purposes. I think that would bring this container to production ready use-cases.

**Comment by fkoester** [comment]
Hi, thanks for your input!

This is already possible with the current version of letsencrypt-manager, you can add as many domains to an certificate as letsencrypt allows:

```
letsencrypt-manager add <main domain name> [alternative domain names]...
```

Have you tried that? Please let me know if you have any problems.
