### ISSUE TITLE
certbot: No such file or directory

### ISSUE THREAD

**Issue by cornernote** [bringnow/docker-letsencrypt-manager#12]
```
# letsencrypt-manager add any-domain.com
Adding domain "any-domain.com"...
/usr/local/bin/entrypoint.sh: line 64: /opt/certbot/venv/bin/certbot: No such file or directory
Failed to issue certificate 
```

**Comment by snowkeep** [comment]
Seems to be the same problem:
&gt; letsencrypt-manager renew any-domain.com
Renewing domain "any-domain.com"...
/usr/local/bin/entrypoint.sh: line 102: /opt/certbot/venv/bin/certbot: No such file or directory
letsencrypt returned error code 127

&gt; letsencrypt-manager auto-renew
Executing auto renew at Thu, 10 May 2018 23:42:04 +0000
Renewing domain "any-domain.com"...
/usr/local/bin/entrypoint.sh: line 102: /opt/certbot/venv/bin/certbot: No such file or directory
letsencrypt returned error code 127
[error] failed to renew certificate for any-domain.com!

**Comment by cguentherTUChemnitz** [comment]
Some problem for me.
I assume this commit introduces the problem:
https://github.com/bringnow/docker-letsencrypt-manager/commit/7f85608960398db03096885d63e75b7d0afedd3a

When i run in the newly used base image a find to the not found binary, i get the following results:

```
find / -name certbot
/usr/local/bin/certbot
/opt/certbot
/opt/certbot/src/certbot
```

This highlights that the /usr/local/bin/entrypoint.sh looks at the wrong place for the certbot binary.

**Comment by cguentherTUChemnitz** [comment]
When i patch the entrypoint.sh to point to the exisiting certbot binary, i get the following error:

```
./letsencrypt-manager add blabla.tld
Adding domain "blabla.tld"...
Unknown command certonly
Failed to issue certificate 
```

**Comment by gitsf** [comment]
I have been have the same problem.
I changed entrypoint.sh line to LE_CMD="certbot certonly ${LE_EXTRA_ARGS}"
however to get it to use this file, I had to change the docker-compose.yml file and remove image and add a dockerfile reference to the local dockerfile. 
After doing this it did succesfully renew a few of my certificates that were expired. However I also have the problem that when I run letsencrypt-manager list
It gives an error for each certificate saying "date: invalid date 'Jun 22 23:00:51 2018 GMT'"
The dates are different for each one, according to when it expires. So the ones that were just renewed still give this error, so renewing them didnt update the date format for them.
Then in the normal grid/table the far right column that shows remaining days ALL say -17672
No matter what date is listed as the actual expire date they all show -17672 for the remaining days

**Comment by snowkeep** [comment]
I noticed the expiry issue, too.  It shows the correct date, but "-17672" remaining days.
My certificates were expiring this week, and I didn't want to fight with this tool, so I did it manually inside my nginx container.  Not as elegant as letsencrypt-manager, but it worked:
```
docker exec -it core_nginx_1 /bin/bash
echo deb http://ftp.debian.org/debian stretch-backports main >> /etc/apt/sources.list
apt-get update
sudo apt-get install python-certbot-nginx -t stretch-backports
certbot renew
```

**Comment by gitsf** [comment]
I have never used git for trying to modify and submit file changes, but I think I did it correctly. I proposed a change to entrypoint.sh to change the path for certbot to /usr/local/bin
Changing this seems to fix it for me.
This just leaves the Date errors, I am going to try and tackle that problem next if possible.

**Comment by gitsf** [comment]
To fix the date error, we need to install the coreutils package in the image. I just sent the pull request to fix it.
Now for the Cron error, anyone else getting:
/usr/local/bin/entrypoint.sh: line 276: /etc/cron.d/letsencrypt: No such file or directory
/usr/local/bin/entrypoint.sh: line 277: cron: command not found

Yes I probably should open new issues, but oh well for now

**Comment by gitsf** [comment]
@cornernote @snowkeep @cguentherTUChemnitz 
for anyone interested,
I have forked this project and made my modifications. If bringnow returns and makes some updates I can switch back but for now this is working for me and hopefully helps others out there.
Anyone interested can check it out [Github page](https://github.com/gitsf/docker-letsencrypt-manager) or [Docker Hub page](https://hub.docker.com/r/dockersf/letsencrypt-manager/)
If you need any help converting to it just let me know.

**Comment by fkoester** [comment]
Thank you very much @gitsf! 

Unfortunately me and the rest of the @bringnow team do not have the time to maintain this project anymore. So I am happy that you are stepping in and I will update the readme to link to your project page.

**Comment by cornernote** [comment]
@gitsf Thanks for keeping this working.  I have been using your repo for a while.

I had to do a reinstall just now, and I'm getting this:

```
An unexpected error occurred:
The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

Your branch doesn't allow issues to be submitted, so I hope you see this.

**Comment by gitsf** [comment]
I will look at it tomorrow, I am out of town today. I honestly haven't been
using this myself for awhile now. I have switched to a traefik container
that does certificates built in.
I will definitely take a look and try to keep this working for you.

-- Sent from my mobile device so please excuse any grammatical errors

**Comment by gitsf** [comment]
Looks like that is because ACMEv1 is no longer supported. I will need to try and update it to use ACMEv2.

**Comment by FelikZ** [comment]
It seems that just rebuilding @gitsf 'repo will get latest certbot and it should use ACMEv2 by default.
