### ISSUE TITLE
cron service does not work with overlay storage driver: tail: unrecognized file system type 0x794c7630 for '/var/log/cron.log'

### ISSUE THREAD

**Issue by fkoester** [bringnow/docker-letsencrypt-manager#2]
When using docker together with the [overlay storage driver](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/), the cron service of letsencrypt-manager fails to start. Log says:

``` bash
Attaching to dockerletsencryptmanager_cron_1
cron_1  | tail: unrecognized file system type 0x794c7630 for '/var/log/cron.log'. please report this to bug-coreutils@gnu.org. reverting to polling
ERROR: Aborting.
```

**Comment by fkoester** [comment]
Fixed, please update.

**Comment by pkill37** [comment]
Thanks! Your fix was helpful in my own problem.

**Comment by fkoester** [comment]
@faviouz Glad I could help! For later reference: The root cause of this problem is that the version of `tail` (package `coreutils`) in the Debian base image is too old and does not know the overlay filesystem. Using a docker volume for `/var/log` works around this by using the host's filesystem (ext4 in my case) and `tail` does not need to know overlay.

**Comment by tiny1990** [comment]
can you tell me how to fix this? which PR

**Comment by fkoester** [comment]
@tiny1990 https://github.com/bringnow/docker-letsencrypt-manager/commit/7a157dcd05ea8e745ec604734f6e7aa2e9e7b7cc
