### ISSUE TITLE
Host path?

### ISSUE THREAD

**Issue by bitwombat** [bringnow/docker-letsencrypt-manager#7]
In  docker-letsencrypt-manager/docker-compose.yml
you have
````
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
    - /var/acme-webroot:/var/acme-webroot
````

This is binding to my host's file system.  Is this really what's wanted?  I was expecting either a docker volume, or a relative path.

**Comment by fkoester** [comment]
At least that is what I want for my setup. On my host systems I have many (independent) services, that all come with their own `docker-compose.yml`. I do not want to create any dependencies between them and by using host mounted volumes, they all can use the SSL certificates stored in `/etc/letsencrypt`. The HTTP proxy implementing ACME validation can furthermore use the webroot from `/var/acme-webroot`.

This setup might not match your requirements, but you can of course create your own `docker-compose.yml` without host-mounted volumes.

If you have a setup that might be useful to others, please consider creating a Pull Request (don't forget to add documentation).

Hope that answers your question. If not, please reopen this issue.

**Comment by bitwombat** [comment]
Ah, thanks for the explanation Fabian.  Isn't  /etc/letsencrypt a dependency between them?  How would docker volumes be any more of a dependency?

Just trying to understand.  First time I've seen this pattern.

**Comment by fkoester** [comment]
Sure but on a different level. Host-mounted volumes are not different to ordinary data volumes and in fact you can use the images without using host mountpoints, you can just use the same volume between different docker services. I am just using the directory path name as a naming convention for the volumes.

For me this has also the advantage that I can easily integrate non-docker services with `letsesncrypt-manager`.
