### ISSUE TITLE
Ha haproxy setup

### ISSUE THREAD

**Issue by trompx** [bringnow/docker-letsencrypt-manager#9]
Hello @fkoester ,

In the case of a ha haproxy setup:
- 1 domain: example.com
- 2 haproxy docker containers on 2 servers: ip1 and ip2 as A domain for example.com
- 3 nginx webservers docker containers referenced in haproxy.cfg of both haproxy servers for example.com on 3 servers: ip3, ip4 and ip5

Could you advise on the add/renew process for this kind of setup?
When adding a certificate for example.com with the letsencrypt-manager, should I:
- generate the certificate only once: run the letsencrypt-manager container on one of the haproxy server  then rsync the generated file to the other haproxy server
or
- run the letsencrypt-manager container on both haproxy servers

Thanks for the clarification.

**Comment by fkoester** [comment]
For multiple instances sharing the same certificates I implemented synchronization of the `/etc/letsencrypt` folder between the machines. I used a git for this but `rsync` should of course work, too. You can run `letsencrypt-manager` on one or also on all of the hosts, but ensure that they do not modify the `/etc/letsencrypt` directory at the same time to avoid conflicts.
